title: "svetlai"
logo: http://i.imgur.com/S99Sd2W.png
email: svetla_22@yahoo.com
description: >
  Find my projects on <a href='https://github.com/svetlai'>GitHub</a>
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://svetlai.github.io/"

github_username:  svetlai

github_profile: https://github.com/svetlai
linkedin_profile: https://bg.linkedin.com/in/svetla-ivanova-98950a9b

# twitter_username:     example  # Replace this with your Twitter username
# linkedin_username:    example  # Replace this with your LinkedIn username
# google_plus_username: example  # Replace this with your Google+ username
# facebook_username:    example  # Replace this with your Facebook username
# dribbble_username:    example  # Replace this with your Dribbble username

permalink: pretty
paginate: 5

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate

collections:
        projects:
                output: true